Collecting poetry==1.8.2
  Using cached poetry-1.8.2-py3-none-any.whl.metadata (6.8 kB)
Collecting build<2.0.0,>=1.0.3 (from poetry==1.8.2)
  Using cached build-1.2.1-py3-none-any.whl.metadata (4.3 kB)
Collecting cachecontrol<0.15.0,>=0.14.0 (from cachecontrol[filecache]<0.15.0,>=0.14.0->poetry==1.8.2)
  Using cached cachecontrol-0.14.0-py3-none-any.whl.metadata (3.1 kB)
Collecting cleo<3.0.0,>=2.1.0 (from poetry==1.8.2)
  Using cached cleo-2.1.0-py3-none-any.whl.metadata (12 kB)
Collecting crashtest<0.5.0,>=0.4.1 (from poetry==1.8.2)
  Using cached crashtest-0.4.1-py3-none-any.whl.metadata (1.1 kB)
Collecting dulwich<0.22.0,>=0.21.2 (from poetry==1.8.2)
  Using cached dulwich-0.21.7-cp312-cp312-win_amd64.whl.metadata (4.4 kB)
Collecting fastjsonschema<3.0.0,>=2.18.0 (from poetry==1.8.2)
  Using cached fastjsonschema-2.19.1-py3-none-any.whl.metadata (2.1 kB)
Collecting installer<0.8.0,>=0.7.0 (from poetry==1.8.2)
  Using cached installer-0.7.0-py3-none-any.whl.metadata (936 bytes)
Collecting keyring<25.0.0,>=24.0.0 (from poetry==1.8.2)
  Using cached keyring-24.3.1-py3-none-any.whl.metadata (20 kB)
Collecting packaging>=23.1 (from poetry==1.8.2)
  Using cached packaging-24.0-py3-none-any.whl.metadata (3.2 kB)
Collecting pexpect<5.0.0,>=4.7.0 (from poetry==1.8.2)
  Using cached pexpect-4.9.0-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting pkginfo<2.0.0,>=1.9.4 (from poetry==1.8.2)
  Using cached pkginfo-1.10.0-py3-none-any.whl.metadata (11 kB)
Collecting platformdirs<5,>=3.0.0 (from poetry==1.8.2)
  Using cached platformdirs-4.2.0-py3-none-any.whl.metadata (11 kB)
Collecting poetry-core==1.9.0 (from poetry==1.8.2)
  Using cached poetry_core-1.9.0-py3-none-any.whl.metadata (3.5 kB)
Collecting poetry-plugin-export<2.0.0,>=1.6.0 (from poetry==1.8.2)
  Using cached poetry_plugin_export-1.7.1-py3-none-any.whl.metadata (2.8 kB)
Collecting pyproject-hooks<2.0.0,>=1.0.0 (from poetry==1.8.2)
  Using cached pyproject_hooks-1.0.0-py3-none-any.whl.metadata (1.3 kB)
Collecting requests<3.0,>=2.26 (from poetry==1.8.2)
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting requests-toolbelt<2.0.0,>=1.0.0 (from poetry==1.8.2)
  Using cached requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Collecting shellingham<2.0,>=1.5 (from poetry==1.8.2)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting tomlkit<1.0.0,>=0.11.4 (from poetry==1.8.2)
  Using cached tomlkit-0.12.4-py3-none-any.whl.metadata (2.7 kB)
Collecting trove-classifiers>=2022.5.19 (from poetry==1.8.2)
  Using cached trove_classifiers-2024.4.10-py3-none-any.whl.metadata (2.2 kB)
Collecting virtualenv<21.0.0,>=20.23.0 (from poetry==1.8.2)
  Using cached virtualenv-20.25.3-py3-none-any.whl.metadata (4.4 kB)
Collecting colorama (from build<2.0.0,>=1.0.3->poetry==1.8.2)
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting msgpack<2.0.0,>=0.5.2 (from cachecontrol<0.15.0,>=0.14.0->cachecontrol[filecache]<0.15.0,>=0.14.0->poetry==1.8.2)
  Using cached msgpack-1.0.8-cp312-cp312-win_amd64.whl.metadata (9.4 kB)
Collecting filelock>=3.8.0 (from cachecontrol[filecache]<0.15.0,>=0.14.0->poetry==1.8.2)
  Using cached filelock-3.13.4-py3-none-any.whl.metadata (2.8 kB)
Collecting rapidfuzz<4.0.0,>=3.0.0 (from cleo<3.0.0,>=2.1.0->poetry==1.8.2)
  Using cached rapidfuzz-3.8.1-cp312-cp312-win_amd64.whl.metadata (11 kB)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/urllib3/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000017955ED0AD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/urllib3/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000017957D4B950>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/urllib3/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000017957D4BB90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/urllib3/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000017957D4BE00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/urllib3/
INFO: pip is looking at multiple versions of dulwich to determine which version is compatible with other requirements. This could take a while.
Collecting dulwich<0.22.0,>=0.21.2 (from poetry==1.8.2)
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000179568DC110>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/57/e0/1b5f95c2651284a5d4fdfb2cc5ecad57fb694084cce59d9d4acb7ac30ecf/dulwich-0.21.6.tar.gz
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000179568DC470>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/57/e0/1b5f95c2651284a5d4fdfb2cc5ecad57fb694084cce59d9d4acb7ac30ecf/dulwich-0.21.6.tar.gz
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000179568DC5C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/57/e0/1b5f95c2651284a5d4fdfb2cc5ecad57fb694084cce59d9d4acb7ac30ecf/dulwich-0.21.6.tar.gz
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000179568DCA40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/57/e0/1b5f95c2651284a5d4fdfb2cc5ecad57fb694084cce59d9d4acb7ac30ecf/dulwich-0.21.6.tar.gz
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000179568DCBC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/57/e0/1b5f95c2651284a5d4fdfb2cc5ecad57fb694084cce59d9d4acb7ac30ecf/dulwich-0.21.6.tar.gz
ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/57/e0/1b5f95c2651284a5d4fdfb2cc5ecad57fb694084cce59d9d4acb7ac30ecf/dulwich-0.21.6.tar.gz (Caused by NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000179568DCE90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))


Traceback:

  File "<stdin>", line 923, in main
  File "<stdin>", line 560, in run
  File "<stdin>", line 582, in install
  File "<stdin>", line 685, in install_poetry
  File "<stdin>", line 375, in pip
  File "<stdin>", line 372, in python
  File "<stdin>", line 365, in run
